services:

  ollama:
    image: ollama/ollama
    container_name: contractguard-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  backend:
    build: .
    container_name: contractguard-backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434

volumes:
  ollama_data: